name: Build Native Executables
run-name: Build Native Executables - Minesweeper@v${{ inputs.version }}

permissions:
  contents: read
  packages: read

on:
  workflow_dispatch:
    inputs:
      version:
        description: Executable version. Follows SemVer
        required: true
        type: string

jobs:
  build-executable:
    strategy:
      matrix:
        include:
          - os_name: 'Windows'
            runner_name: 'windows-2022'
            command_name: 'windows'
          - os_name: 'Linux'
            runner_name: 'ubuntu-22.04'
            command_name: 'linux'
          - os_name: 'MacOS'
            runner_name: 'macos-12'
            command_name: 'macos'

    name: Build Native - ${{ matrix.os_name }}
    runs-on: ${{ matrix.runner_name }}
    timeout-minutes: 30

    env:
      APP_VERSION: ${{ inputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Java
        uses: actions/setup-java@v2
        with:
          distribution: 'microsoft'
          java-version: '21'

      - name: Sanity Check
        run: |
          echo "Java version"
          java --version
          echo "JPackage version"
          jpackage --version
          echo "Current dir"
          ls -al .
          echo "src dir"
          ls -al ./src/

      - name: Install make - Windows
        if: ${{ matrix.os_name == 'Windows' }}
        run: choco install make

      - name: Install make - MacOS
        if: ${{ matrix.os_name == 'MacOS' }}
        run: brew install make

      - name: Build Jar
        run: make jar

      - name: Build Native Executable
        run: make package-native-${{ matrix.command_name }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Minesweeper v${{ env.APP_VERSION }}
          if-no-files-found: error
          path: |
            jar/Minesweeper-${{ env.APP_VERSION }}.jar
            builds/
