name: Lint Github Workflows

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '.github/**/*.yml'

concurrency:
  group: lint-workflows-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-workflows:
    runs-on: ubuntu-22.04
    timeout-minutes: 20

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install shellcheck
        run: sudo apt-get install -y shellcheck

      - name: Install actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)

      - name: Check workflow files with actionlint
        run: ${{ steps.get_actionlint.outputs.executable }}
